# Generated by Django 4.1 on 2022-11-12 16:51

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('babtyno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='hero_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_venue',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='itinerary_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
