# Generated by Django 4.1 on 2022-11-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babtyno', '0003_homepage_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
