# Generated by Django 4.1 on 2022-11-13 16:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('babtyno', '0004_alter_homepage_hero_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tripanel_nav',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.CharBlock(form_classname='link 1 url')), ('Text', wagtail.blocks.CharBlock(form_classname='link 1 text')), ('image1', wagtail.images.blocks.ImageChooserBlock()), ('link2', wagtail.blocks.CharBlock(form_classname='link 2 url')), ('Text2', wagtail.blocks.CharBlock(form_classname='link 2 text')), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('link3', wagtail.blocks.CharBlock(form_classname='link 3 url')), ('Text3', wagtail.blocks.CharBlock(form_classname='link 3 text')), ('image3', wagtail.images.blocks.ImageChooserBlock())], blank=True, use_json_field=True),
        ),
    ]
