# Generated by Django 4.1 on 2022-11-13 16:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('babtyno', '0006_alter_homepage_tripanel_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='tripanel_nav',
            field=wagtail.fields.StreamField([('imageLink', wagtail.blocks.StructBlock([('link', wagtail.blocks.CharBlock(form_classname='link 1 url')), ('Text', wagtail.blocks.CharBlock(form_classname='link 1 text')), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, use_json_field=True),
        ),
    ]
