# Generated by Django 4.1 on 2022-11-27 00:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('babtynoemail', '0002_guestemail_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveTheDateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.fields.RichTextField()),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.DeleteModel(
            name='GuestEmail',
        ),
    ]
