# Generated by Django 4.1 on 2022-11-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babtynoemail', '0003_savethedateemail_delete_guestemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='savethedateemail',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='savethedateemail',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
