# Generated by Django 4.1 on 2022-11-27 13:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('babtynoemail', '0004_savethedateemail_subject_savethedateemail_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='savethedateemail',
            name='font_colour',
            field=models.CharField(default='#000000', max_length=9),
        ),
        migrations.AddField(
            model_name='savethedateemail',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='savethedateemail',
            name='main_colour',
            field=models.CharField(default='#FFFFFF', max_length=9),
        ),
        migrations.AlterField(
            model_name='savethedateemail',
            name='body',
            field=wagtail.fields.StreamField([('body', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'document-link']))], use_json_field=True),
        ),
    ]
