# Generated by Django 4.1 on 2022-11-29 23:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('babtynoemail', '0006_savethedateemail_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(choices=[('en-gb', 'English'), ('lt', 'Lithuanian')], default=('en-gb', 'English'), max_length=25)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('main_colour', models.CharField(default='#FFFFFF', max_length=9)),
                ('font_colour', models.CharField(default='#000000', max_length=9)),
                ('body', wagtail.fields.StreamField([('body', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'document-link']))], use_json_field=True)),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
