# Generated by Django 4.1 on 2022-12-11 00:29

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('babtynoemail', '0007_rsvpemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvpemail',
            name='rsvp_negative_response_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='rsvpemail',
            name='rsvp_positive_response_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
