# Generated by Django 4.1 on 2023-01-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babtynoemail', '0008_rsvpemail_rsvp_negative_response_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvpemail',
            name='language',
            field=models.CharField(choices=[('en-gb', 'English'), ('lt', 'Lithuanian'), ('fr', 'French')], default=('en-gb', 'English'), max_length=25),
        ),
        migrations.AlterField(
            model_name='savethedateemail',
            name='language',
            field=models.CharField(choices=[('en-gb', 'English'), ('lt', 'Lithuanian'), ('fr', 'French')], default=('en-gb', 'English'), max_length=25),
        ),
    ]
