# Generated by Django 4.1 on 2022-11-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20220807_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
    ]
