# Generated by Django 4.1 on 2022-12-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0022_alter_newlywedsetting_wedding_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newlywedsetting',
            name='site',
        ),
        migrations.DeleteModel(
            name='EmailSettings',
        ),
        migrations.DeleteModel(
            name='NewlyWedSetting',
        ),
    ]
