# Generated by Django 4.1 on 2023-01-07 14:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0023_remove_newlywedsetting_site_delete_emailsettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='guest',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='party',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='guests.party'),
        ),
    ]
