# Generated by Django 4.1 on 2023-01-14 18:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0024_alter_guest_options_guest_sort_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Vegan? Gluten-free? For Anglophones? For non-Anglophones?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='guest',
            name='party',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='guests', to='guests.party'),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.TextField(help_text='Name of the dish')),
                ('comments', models.TextField(help_text="Say if it's vegan, veggie, gluten-free, halal, kosher, etc.")),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, to='guests.menu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
