# Generated by Django 4.1 on 2023-01-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0026_dish_description_alter_dish_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(blank=True, choices=[('app', 'Appetiser'), ('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert')], max_length=20, null=True),
        ),
    ]
