# Generated by Django 4.1 on 2023-01-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0027_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='comments',
            field=models.TextField(blank=True, help_text="Say if it's vegan, veggie, gluten-free, halal, kosher, etc.", null=True),
        ),
    ]
