# Generated by Django 4.1 on 2023-01-14 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0028_alter_dish_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dish', to='guests.guest'),
        ),
    ]
