# Generated by Django 4.1 on 2023-01-14 23:40

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0030_alter_dish_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='guest',
        ),
        migrations.AddField(
            model_name='guest',
            name='dishes',
            field=modelcluster.fields.ParentalManyToManyField(related_name='dish', to='guests.dish'),
        ),
    ]
