# Generated by Django 4.1 on 2023-01-15 12:22

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0032_alter_guest_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dishes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, related_name='dishes', to='guests.dish'),
        ),
    ]
