# Generated by Django 4.1 on 2023-01-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0033_alter_guest_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='dishes',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
