# Generated by Django 4.1 on 2023-01-15 12:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('guests', '0034_remove_guest_dishes_delete_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('type', models.CharField(blank=True, choices=[('app', 'Appetiser'), ('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert')], max_length=20, null=True)),
                ('title', models.TextField(help_text='Name of the dish')),
                ('description', models.TextField(blank=True, help_text='Description of the dish', null=True)),
                ('comments', models.TextField(blank=True, help_text="Say if it's vegan, veggie, gluten-free, halal, kosher, etc.", null=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish', to='guests.menu')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
