# Generated by Django 4.1 on 2023-01-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0036_guest_dishes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
    ]
