# Generated by Django 4.1 on 2023-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0037_alter_dish_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='dishes',
        ),
        migrations.AddField(
            model_name='guest',
            name='dishes',
            field=models.TextField(blank=True, choices=[(1, 'Appetiser #1'), (2, 'Starter #1'), (3, 'Main #1'), (4, 'Dessert #1'), (5, 'Ice cream'), (6, 'Smirdas'), (7, 'Brocolis su burokėlis'), (8, 'Antys'), (9, 'Karšta kava'), (10, 'Arbata'), (12, 'Starter #2')], null=True),
        ),
    ]
