# Generated by Django 4.1 on 2023-04-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0039_alter_guest_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='meal',
        ),
        migrations.AddField(
            model_name='guest',
            name='dessert',
            field=models.CharField(blank=True, choices=[('4', 'Dessert #1'), ('5', 'Ice cream'), ('9', 'Karšta kava'), ('10', 'Arbata')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='main',
            field=models.CharField(blank=True, choices=[('3', 'Main #1'), ('8', 'Antys')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='starter',
            field=models.CharField(blank=True, choices=[('2', 'Starter #1'), ('7', 'Brocolis su burokėlis'), ('12', 'Starter #2')], max_length=100, null=True),
        ),
    ]
